# ifdef CONFIG_PRODUCT_REALME_TRINKET
# geyixue@BSP.Driver, 2014/07/29, Add for OPPO device info
#obj-$(CONFIG_RECORD_MDMRST)	+=  oppo_mdmrst.o
obj-y	+=  oppo_mdmrst.o
# endif /* CONFIG_PRODUCT_REALME_TRINKET */
