#ifdef CONFIG_ODM_WT_EDIT
#/* Bin2.Zhang@ODM_WT.BSP.Charger.Basic.1941873, 20200406, Add for macro CONFIG_ODM_WT_EDIT */
subdir-ccflags-y += -DCONFIG_ODM_WT_EDIT
#endif /* CONFIG_ODM_WT_EDIT */

obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

#ifdef CONFIG_PRODUCT_REALME_TRINKET
#/* Zhangchangan  PSW.BSP.CHG  2019-10-30 */
obj-$(CONFIG_OPPO_SM6125Q_CHARGER)	+= oppo/
#endif
